language: python

git:
  # Testing doesn't need Flask themes.
  submodules: false

matrix:

  include:

    # 3

    - python: "3.7"
      env: FLASK_VERSION=""
      os: linux

    - python: "3.7"
      env: FLASK_VERSION="==1.0"
      os: linux

    - python: "3.7"
      env: FLASK_VERSION="==0.10"
      os: linux

    # 2

    - python: "2.7"
      env: FLASK_VERSION=""
      os: linux

    - python: "2.7"
      env: FLASK_VERSION="==1.0"
      os: linux

    - python: "2.7"
      env: FLASK_VERSION="==0.10"
      os: linux

    - python: "2.7"
      env: FLASK_VERSION="==0.9"
      os: linux

    # PyPy.

    - python: "pypy"
      env: FLASK_VERSION=""
      os: linux

    - python: "pypy"
      env: FLASK_VERSION="==0.10"
      os: linux
      
    # Older 3s.

    - python: "3.6"
      env: FLASK_VERSION=""
      os: linux

    - python: "3.5"
      env: FLASK_VERSION=""
      os: linux

    - python: "3.4"
      env: FLASK_VERSION=""
      os: linux


before_install:
  - sudo apt-get install libjpeg8 libjpeg8-dev libfreetype6 libfreetype6-dev zlib1g-dev tree
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so.8 ~/virtualenv/python2.7/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so ~/virtualenv/python2.7/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so ~/virtualenv/python2.7/lib/
  - pip install nose


install:
  - pip install Flask$FLASK_VERSION
  - pip install -e .


script: nosetests
